### ISSUE TITLE
这是个提问题的好地方啊

### ISSUE THREAD

**Issue by zhuwhr** [robturtle/CS-Skills#2]

**Comment by robturtle** [comment]
如果还不会用 `Markdown` 语法的话，点击编辑框右上角的 `Styling with Markdown is supported` 来学习。很简单的。

包括插入代码：

```java
public static void main(String[] args) {
  ...
}
```

**Comment by robturtle** [comment]
每一个不相关的问题分别开一个issue即可。这个issue我现在关了。
